#!/usr/bin/env python3
"""
Turn ML Predictions into FHIR RiskAssessments

You have a model that outputs risk scores. To get those scores into an EHR —
where clinicians, dashboards, and quality measures can use them — they have to
become FHIR RiskAssessment resources. This example does exactly that: take the
predictions your model already produced and emit spec-valid FHIR, one resource
per patient.

Bring your own model. This script uses a pre-baked predictions dict so it runs
offline with zero setup — no model file, no schema, no server. Swap in your own
model's output and the rest is unchanged.

Requirements:
- pip install healthchain

Run:
    python cookbook/ml_risk_to_fhir.py
    # Builds RiskAssessment resources from predictions and prints them.
    # Set MEDPLUM_* env vars to also write them back to a live FHIR server.
"""

import json
import os

from dotenv import load_dotenv

from healthchain.fhir import create_bundle, add_resource
from healthchain.fhir import create_risk_assessment_from_prediction

load_dotenv()


# --- Your model's output ---------------------------------------------------
# Whatever your model is — XGBoost, a neural net, a scikit-learn pipeline — the
# only thing HealthChain needs is the score. Here are three patients your model
# has already scored for sepsis risk.
PREDICTIONS = {
    "Patient/1": {"probability": 0.85, "qualitative_risk": "high"},
    "Patient/2": {"probability": 0.52, "qualitative_risk": "moderate"},
    "Patient/3": {"probability": 0.09, "qualitative_risk": "low"},
}

# The outcome your model predicts — coded once, applied to every assessment.
SEPSIS = {
    "code": "A41.9",
    "display": "Sepsis, unspecified organism",
    "system": "http://hl7.org/fhir/sid/icd-10",
}


def build_risk_assessments():
    """Turn each prediction into a FHIR RiskAssessment, collected in a Bundle."""
    bundle = create_bundle()

    for subject, scores in PREDICTIONS.items():
        risk = create_risk_assessment_from_prediction(
            subject=subject,
            prediction={
                "outcome": SEPSIS,
                "probability": scores["probability"],
                "qualitative_risk": scores["qualitative_risk"],
            },
            comment="Generated by sepsis-risk model v1",
        )
        add_resource(bundle, risk)

    return bundle


def write_back(bundle):
    """Optionally persist the assessments to a live FHIR server.

    This is the point of producing FHIR: the resources land in the EHR, where
    they show up in dashboards, reports, and downstream workflows. Configure a
    source with credentials and the gateway writes each one back.
    """
    from healthchain.gateway import FHIRGateway
    from healthchain.gateway.clients import FHIRAuthConfig

    gateway = FHIRGateway()
    gateway.add_source(
        "medplum", FHIRAuthConfig.from_env("MEDPLUM").to_connection_string()
    )

    for entry in bundle.entry:
        created = gateway.create(entry.resource, source="medplum")
        print(f"  wrote RiskAssessment/{created.id} to medplum")


if __name__ == "__main__":
    bundle = build_risk_assessments()

    print(f"Built {len(bundle.entry)} RiskAssessment resources:\n")
    for entry in bundle.entry:
        ra = entry.resource
        pred = ra.prediction[0]
        risk = pred.qualitativeRisk.coding[0].code
        print(
            f"  {ra.subject.reference}: {risk.upper()} "
            f"({pred.probabilityDecimal:.0%}) → RiskAssessment/{ra.id}"
        )

    # Show the first resource as FHIR JSON.
    print("\nExample RiskAssessment:\n")
    print(json.dumps(bundle.entry[0].resource.model_dump(exclude_none=True), indent=2))

    # Take it live: write the assessments back to a FHIR server if configured.
    if os.getenv("MEDPLUM_CLIENT_ID"):
        print("\n=== Writing back to Medplum ===")
        write_back(bundle)
